### ISSUE TITLE
Compilation error:  cannot use ^translatable_type outside of match clauses

### ISSUE THREAD

**Issue by thojanssens** [smeevil/ecto_translate#10]
Following schema module generates the error:

```
defmodule MyApp.Foo do
  use Ecto.Schema
  use EctoTranslate, [:some_translatable_field]

  schema "foo" do
    field(:some_field, :string)
    field(:some_translatable_field, :string)
  end
end
```

> == Compilation error in file lib/foo/foo.ex ==
> ** (CompileError) lib/my_app/foo.ex:3: cannot use ^translatable_type outside of match clauses
>     (stdlib) lists.erl:1354: :lists.mapfoldl/3
>     (stdlib) lists.erl:1355: :lists.mapfoldl/3
>     (elixir) expanding macro: Kernel.|>/2

According do [this stackoverflow post](https://stackoverflow.com/questions/38844103/cannot-use-xxx-outside-of-match-clauses), an import Ecto.Query is missing.

I think that EctoTranslate should make sure it is imported.

**Comment by thojanssens** [comment]
Later on it says in the docs:
> Important: Don't forget to import Ecto.Query before use EctoTranslate

However, it would be nice to show the import in the first snippet of the docs as well. 

Also, can't EctoTranslate import it when using EctoTranslate? I'm really just starting out with Elixir, so just wondering why not import Ecto.Query from `EctoTranslate.__using__/1`.

**Comment by thojanssens** [comment]
https://github.com/smeevil/ecto_translate/compare/master...thojanssens:patch-1

**Comment by alisinabh** [comment]
Hi @thojanssens,

I've created a PR #16 from your changes to README.md.

Thanks for your collaboration.

Cheers :heart:
