### ISSUE TITLE
warning: function nil.all/1 is undefined (module nil is not available)

### ISSUE THREAD

**Issue by thojanssens** [smeevil/ecto_translate#11]
Every time I run or compile my app, I get the following warnings:

> warning: function nil.all/1 is undefined (module nil is not available)
>   lib/my_app/foo.ex:4

> warning: function nil.one/1 is undefined (module nil is not available)
>   lib/my_app/foo.ex:4

line 4 is where I `use EctoTranslate`

Schema:

```
defmodule MyApp.Foo do
  import Ecto.Query
  use Ecto.Schema
  use EctoTranslate, [:some_translatable_field]

  schema "foo" do
    field(:some_field, :string)
    field(:some_translatable_field, :string)
  end
end
```

Am I doing something wrong?

**Comment by alisinabh** [comment]
I think you've missed step 6 in README.md

6. Update your config.exs and add these settings

```elixir
 config :ecto_translate, repo: MyApp.Repo, gettext: MyApp.Gettext
 ```

Don't forget to change `MyApp` with your application name.

**TIP:** Maybe clean your deps with `mix deps.clean ecto_translate` and try again after setting the configuration.
