### ISSUE TITLE
is [applications: [:ecto_translate]] really necessary?

### ISSUE THREAD

**Issue by thojanssens** [smeevil/ecto_translate#12]
In the docs it is mentioned:

> 2. Ensure ecto_translate is started before your application:
> 
> def application do
>   [applications: [:ecto_translate]]
> end

But is this really necessary?

When I get information about the `:applications` option with `mix help compile.app` I read the following:

>   * `:applications` - all applications your application depends
>     on at runtime. By default, this list is automatically inferred
>     from your dependencies. Mix and other tools use the application
>     list in order to start your dependencies before starting the
>     application itself.

it says "_this list is automatically inferred from your dependencies_".

**Comment by alisinabh** [comment]
From elixir 1.3+ this is not necessary but still harmless to add :)
