### ISSUE TITLE
Works for ecto_sql 3.0 but not 3.1

### ISSUE THREAD

**Issue by thojanssens** [smeevil/ecto_translate#13]
If I have `{:ecto_sql, "~> 3.1"}` in my list of deps, it is causing this error:

> Failed to use "ecto" (versions 3.1.0 to 3.1.6) because
>   ecto_sql (versions 3.1.0 to 3.1.5) requires ~> 3.1.0
>   ecto_translate (version 1.0.0) requires ~>3.0.7

I have to downgrade my ecto_sql version to 3.0.

**Comment by alisinabh** [comment]
I know it's a bit late, But you can add this to your dependencies to fix this until the next compatible version of ecto_translate.

```elixir
{:ecto, "~> 3.1", override: true}
```

P.S. Since ecto 3.1 vs 3.0 api change was only the deprecation of LogEntry and ecto_translate does not use that, I believe you won't be facing any problems.
