### ISSUE TITLE
Not able to migrate

### ISSUE THREAD

**Issue by thojanssens** [smeevil/ecto_translate#14]
This is an issue that blocks me from using this package:

> C:\data\projects\elixir\my_app>mix ecto_translate.gen.migration
> * creating _build/dev/lib/my_app/priv/repo/migrations
> * creating _build/dev/lib/my_app/priv/repo/migrations/20190622103737_ecto_translate_table.exs
> 
> C:\data\projects\elixir\my_app>mix ecto.migrate
> 
> 12:40:02.475 [info]  Already up

The migration files are being added in `_build` as you can see in the output logs above. And when running `mix ecto.migrate` they are not taken into account. However my own migration files in `priv/repo/migrations` are being run.

**Comment by alisinabh** [comment]
Hi @thojanssens,

Can you please try and run `mix ecto.gen.migration test_ecto_translate` on the same machine and see if the migrations will still be added in `_build` directory?

**Comment by alisinabh** [comment]
This issue will be closed due to lack of activity.
